### ISSUE TITLE
Allow anonymous users to create an account during checkout

### ISSUE THREAD

**Issue by wcorkill** [givingforum/givingforum#117]
During early testing we identified that you could allow anonymous users to checkout and create an account during check out.  The users were prompted to create a Drupal account during checkout which was very user friendly.  This streamlined the process for new users that wanted to signup for an event.  I propose that we re-enable this feature with some additional enhancements to correct some of the issues that forced us to disable this feature earlier this year.

The problem was, this process only created a Drupal User account, there was no RedHen user record created, no additional profile information captured and therefore no record of the user in Salesforce.  After discussing enabling/fixing this with Thinkshout, Tauno suggested we revisit the need and level of effort required to correct the identified problems and allow anonymous users to create accounts during checkout.  This is controlled by permissions so each RA could enable or disable this ability for anonymous users.  We also discussed that the creation of the RedHen user account may be fixed but needs to be checked and additional changes are still required as outlined below.

I would also suggest that Thinkshout make sure that it alerts a user and prevents them from creating an account if they already have an existing Drupal/RedHen account.  

We also need Thinkshout to enhance the Checkout Account setup screen to include the same minimum fields that we require to setup a new account as the current form only asks for a name and email address, which is much less than we require to create an account.

**Comment by vrozansky** [comment]
Resolving in favor of tcket #181
