### ISSUE TITLE
Primary Contact able to edit org profile through directory

### ISSUE THREAD

**Issue by canheier** [givingforum/givingforum#120]
would be interested in exploring the possibility for the primary contact (only) at our member orgs to have access to edit the organization profile for the directory. I think this feature should only be available to members at the organization where they are the primary contact. Fields to edit:
-address (address, city, state, zip, county)
-phone
-fax
-email
-website
-mission/goals
-year founded
-staff size range
-types of support
-geo funding areas
-funding areas
-facebook, twitter, linkedin
-category

Please add other fields that should be editable by primary contacts or suggest which of the above should be removed from the list. Any other requirements?

**Comment by vrozansky** [comment]
Resolved with release 2.7.5 and administrative contact roles.
