### ISSUE TITLE
Question: Directory Views based on user role

### ISSUE THREAD

**Issue by canheier** [givingforum/givingforum#124]
I set up committee lists and rosters and I'm a little stuck on how you can hide a field (only one - not all) depending on user role. When you view the directory as a non-member you only see org name and email but as an active member you see other information. For rosters how can we have the roster include email addresses only when the person viewing the list is signed in as an active member. For auth users/anon users it would only show the name and title. Is that possible? 

https://drive.google.com/file/d/0B9QQVjpIBnoAQjl6OC1KMzdGeW8/edit?usp=drivesdk

**Comment by vrozansky** [comment]
we've been handling this via theming in code and it's been working well. Resolving for now, but please feel free to re-open. Thank you.
