### ISSUE TITLE
Add Image/logo Field to RedHen Org Records

### ISSUE THREAD

**Issue by wcorkill** [givingforum/givingforum#128]
On a recent advisory call we discussed interest in adding an image field to RedHen Org records so we could add Logos to these records.  This would then allow us to display the org logos in directory views if you wanted to display this.  We would like to be able to make the directory more visually appealing and think this would be a great addition.

Please let us know if you would be interested in such an option and if there is enough interest we can get the field added to the distribution.

**Comment by vrozansky** [comment]
Deadline for this ticket is August 10th, 2015. I haven't heard the need to add org logos to the directory but we have an option to do that via theming. Mapping to SF will require TS involvement. Please weigh in so we can determine who's interested and whether we need to move this forward as a group or individual RA/s. Thank you.

**Comment by sgeis** [comment]
Indiana is not interested at this time.

**Comment by mtrimbach** [comment]
CNJG not interested.

**Comment by kristenruff** [comment]
On second thought, PNY no longer interested. While I like the idea of including logos in the member directory, I think it would be difficult to make them all look great since they have difference sizes and shapes and would need to conform to a standard spec. We aren't interested in devoting resources to this right now.

**Comment by vrozansky** [comment]
Resolving due the lack of interest. However, our member directory includes the Org logo fields and I've seen early samples from themers that included these. Pretty difficult to maintain, but not impossible. @wcorkill made good suggestions to streamline upkeep. Please re-open if there's an increased interest/need in this functionality. Thank you.
