### ISSUE TITLE
Authorization Code for Events (to allow/block registration)

### ISSUE THREAD

**Issue by canheier** [givingforum/givingforum#131]
Scenario: create authorization code for specific event - users must enter code to move on to register. This could be used if you want to restrict registration for an event to a specific group. 
 
1. Added the authorization code field to line item types http://test-scg.gotpantheon.com/admin/commerce/config/line-items/product/fields.
 
2. Added some custom CSS to tell it to only display on one event http://test-scg.gotpantheon.com/events/test-event-show-code:
 
/* --  displays auth code on following events -- */
#node-event-733 #edit-line-item-fields-field-authorization-code {display: block;}
 
/* --  hides auth code on all other events -- */
#edit-line-item-fields-field-authorization-code {display: none;}
 
3. Created rule that should only apply to one product based on sku: http://test-scg.gotpantheon.com/admin/config/workflow/rules/reaction/manage/rules_authorization_code_check
-- Rule shows message when the code is wrong (this works).

-- If the code is wrong, the rule should clear the contents of the shopping cart (this does not work). Instead, it adds the product to cart but also gives you the message that the code is wrong. https://docs.google.com/file/d/0B9QQVjpIBnoAV2hZc1FzVEVENEU/edit?usp=drivesdk
 
-- If the code is correct, proceed as normal – product is added to cart (this works).
 
There’s two issues here:
#1 – In order to make the authorization code actually block the user you have to make it a required field. However, it looks like doing so has to be done at the line item level making it required for all events.  Even though you can’t see the authorization code (because of the custom css) on other events like http://test-scg.gotpantheon.com/events/focus-stemarts-education-amplifying-collective-impact when you click register you get the message that the authorization code is required. How can we get around this?
 
#2 – it doesn’t seem like the “remove all products from cart” is actually working here…it doesn’t empty the cart. Maybe there’s a better way to organize this – could the authorization code be required at a different stage of the process? The user could add the item to their cart and then when they click “checkout” are prompted to enter the code? At that point the product is in their cart and if the code is wrong, the rule would empty the cart?

**Comment by vrozansky** [comment]
@dbradyforum - please capture documentation in this ticket for our Wiki and resolve this ticket. Thank you.
