### ISSUE TITLE
Linkit links to node URLs, not to SEO-friendly URLs

### ISSUE THREAD

**Issue by jonstahl** [givingforum/givingforum#142]
I've noticed that Linkit, when linking to pages within our site, generates links to non-SEO-friendly URLs, e.g. "/node/XXX" rather than to the pathauto-generated urls, e.g. "/resources/name-of-resource." Not only does that look not so great, it's a bit confusing for users and may ultimately harm our SEO by having the same content available at multiple URLs.

This appears to be a known issue: https://www.drupal.org/node/1462330, and in that thread, using the Pathologic module is suggested as a solution. https://www.drupal.org/project/pathologic.

**Comment by allenlaurie** [comment]
CCP - Yes

**Comment by vrozansky** [comment]
Pathologic module was added to the distro in the 2.7.0 release. Resolving.
