### ISSUE TITLE
Membership Renewal - custom project for Donors Forum

### ISSUE THREAD

**Issue by vrozansky** [givingforum/givingforum#143]
Thanks again to everyone that joined us at the KM User's Group gathering in San Diego. We demoed lots of different features that were developed for various RAs and, as agreed, are now opening them up for group discussion to determine the level of interest from participating RAs and possibly inclusion into our common Salesforce package (or a new custom package). I'll file several tickets to cover different features and link to the recording that you can also find on Basecamp and Wiki.

Membership renewal functionality that was developed by Brian for the Donors Forum received lots of interest. Please see the recording here - http://youtu.be/MvSHbwCUaSo (the first 25 minutes) - and submit your comment/vote on whether you'd be interested in including this functionality in the next version of the common package. Depending on the level of interest in this ticket, we'll see whether it makes sense to do this in the common package and how much will it cost each RA. Donors Forum will be credited for their initial investment. Thank you.

**Comment by vrozansky** [comment]
@kcookedf - lots of time has passed but there's still interested in this feature that I know has been customized for DF by Brian. Can you please share the total cost for this feature so we can determine an approximate amount for each interested RA? There'll most likely be some additional cost per RA unless we have a joint need and can perhaps make it part of our common package or create a parallel package. Thank you.

**Comment by kimsnipes** [comment]
And, as I mentioned last week, if cost prohibitive to create this through Brian/Visualforce pages, we can definitely use Process Builder/Flow to create membership opportunities as you close the current year's record. @agoldhagen, @wcorkill and I have done some work on this already.

**Comment by EmilyBaron** [comment]
GWP will most likely take advantage of using Process Builder/Flow to create membership opportunities.  We aren't interested in this feature at this time.

**Comment by mtrimbach** [comment]
CNJG is not interested.

**Comment by PhilOhio** [comment]
POH would also like to work with process builder/flow to keep costs low.

**Comment by vrozansky** [comment]
I'll resolve this ticket in light of the recent demos on Process Builder/Flow during the User's Group in Baltimore. Please refer to recordings for more information. Thank you.
