### ISSUE TITLE
Include/sync "sort name" in Drupal from Salesforce

### ISSUE THREAD

**Issue by wcorkill** [givingforum/givingforum#148]
1. Sync the organization "sort name" from SF to Drupal by creating a new field in RedHen and customizing mappings.
2. Alter the sort order of organizations in the directory to use this field to sort org names.  

Jon provided the following examples: _e.g. “Bill & Melinda Gates Foundation” should alphabetize under “G” so their “sort name” is “Gates Foundation” and “The Blahdeblah Foundation” should alphabetize under “B” not “T” so their sortname is “Blahdeblah Foundation.”_

**Comment by vrozansky** [comment]
Completed. Resolving.
