### ISSUE TITLE
Multiple Contacts w/ Same E-mail

### ISSUE THREAD

**Issue by DNTownsend** [givingforum/givingforum#149]
Philanthropy Southwest is grappling with an issue and we’d like your input about next steps, and whether to get TS involved. When we migrated data from our former ams/ cms we migrated a number of member contacts with the same email address. We have a large number of trustees involved in our organization, and many elect to have all communications handled by a foundation staff person. Therefore, we might have six trustees + one staff person with an identical email address. In some cases (gmail, Hotmail), adding the +1 “hack” resolves the need for unique email identifiers. However, we still have a large number for whom that solution won’t work. 

Asking the affected users for valid (non-duplicative) email addresses is our next step, as  well as offering the option not to have an email address associated with their account at all. Without an email address, however, the individual will not be included in the “register other user” option during registration checkout. 

The issue at hand is how do we handle those duplicates already in Drupal? For those who elect not to give us an email address, clearing that information from SF is step one, but as Val/Dan pointed out in yesterday’s email, the Drupal user account is not updated and the duplicate remains.  This presents issues for anyone attempting to log in who shares the duplicate email (the staff person!);  It tells them the email address already exists and doesn't let them create a new password. Populating the email field with a fake email updates the Drupal record, but then displays an incorrect email via the Member Directory. 

Tauno has suggested to Val a workflow which automatically updates the Drupal Record when the RedHen record is updated, but we’d like others to weigh in if that’s something you’d like to pursue.

**Comment by EmilyBaron** [comment]
gwp is not intrested at this time
