### ISSUE TITLE
Print View/Layout

### ISSUE THREAD

**Issue by canheier** [givingforum/givingforum#150]
Is it possible to improve the print layout for the sites? When you click on the little print icon (https://docs.google.com/file/d/0B9QQVjpIBnoATWdWMmJRMFVwQTg/edit?usp=drivesdk) or if you just print a page it will print the content, the sidebar content below it, the footer, etc. with lots of space between items. Would it be possible to have the print layout only capture the content of the page/node?

**Comment by vrozansky** [comment]
We actually added this module to the Forum's site in an effort to create a printable event roster. We also had to modify this module a bit to work with our distro. If there's still interest in this task, it's pretty clear that there won't be a distro-wide solution for this and we'll need to work individually with each interested RA. If you're one of these RAs, please contact me offline with your requirements. Thank you. Resolving.
