### ISSUE TITLE
Add Nonprofit Role 

### ISSUE THREAD

**Issue by canheier** [givingforum/givingforum#154]
Create additional role to assign to users (nonprofits) who are allowed to attend certain events but should not have access to events where all "authenticated users" can register. Having this additional role would allow you to have another set of users that can register for certain events only and basically have anonymous user permissions aside from that.

**Comment by canheier** [comment]
Hi All, 
I'd like to get an estimate from TS for this ticket. WRAG would benefit from this additional role in order to streamline their event registration process and allow for an additional user type that does not have access to funder-only events. Please weigh in if you might be interested in adding this to your site as well. Thanks!

**Comment by kristenruff** [comment]
Charlotte, are you trying to make events open to more people or fewer people? 

Most of our event registration is open to all logged in users so non-member funders can register online. However, we often get logged in users registering who are not eligible to attend. We would really like to limit registration based on account record type so only people with an account record type = to funder may register. 

I definitely would like to explore this with ThinkShout but I'm not sure if we have the same needs.

**Comment by vrozansky** [comment]
Resolving in favor of #187
