### ISSUE TITLE
Add SF field "Event Type" to Drupal Mappings (in distro)

### ISSUE THREAD

**Issue by kimsnipes** [givingforum/givingforum#155]
Add the Salesforce Campaign picklist field - "Event Type" to the distro Drupal mappings. Currently, this field is manually updated in Salesforce after the Campaign record is created.

**Comment by vrozansky** [comment]
This has been done.

One thing to note is that the Event Type field in Salesforce is multiple value, while the Drupal field has always been single-value. When pushing from Drupal to Salesforce, everything is fine. But if there happen to be more than one set in Salesforce, only the first one is used when pulling from SF into Drupal. It's probably a rare situation anyway.

**Comment by kristenruff** [comment]
Quick question...We categorize events differently in Drupal than in SF so we will not want to map this field. Once this is included in the distribution, we will need to delete the mapping every time there is an distribution release?

**Comment by vrozansky** [comment]
Yes, you can always disable this particular mapping. Not all releases include updates to SF mappings, but if they do, you'll want to make sure that this one is disabled. Alternatively, you'll see an error in the log and in your integration if it can't find matching values between SF and Drupal (sort of a prompt to disable that mapping).
