### ISSUE TITLE
Add ability to map hierarchical Drupal vocabularies to flat Salesforce picklists

### ISSUE THREAD

**Issue by jonstahl** [givingforum/givingforum#163]
At PNW, we have the need to be able to offer some hierarchical vocabularies for our member directory, e.g.

* Education
  * Early childhood
  * Secondary
  * Post secondary

Drupal has great support for this; however, some challenges arise if we want to map this kind of vocab structure over to Salesforce. Salesforce has limited support for hierarchical vocabulary, and the current Salesforce/Drupal integration suite doesn't support the concept.

We are going to commission ThinkShout to spend a few hours adding a basic version of this to the Salesforce/Drupal integration package, which will give us the following capabilities:

1. The ability to map a hierarchical vocabulary onto a flat Salesforce picklist field, with the values formatted like this (Education : Early Childhood)
1. The ability to sync this bidirectionally between Salesforce and Drupal
1. Vocabulary terms must be unique for the mapping to work (e.g. can't have Maine: Portland and Oregon: Portland)

If you're interested in this, let us know. Currently Tauno has this at about 4 hours, so it's cheap if you want to buy in.

**Comment by EmilyBaron** [comment]
GWP is not interested at this time

**Comment by AClay2** [comment]
PSW is interested.

**Comment by canheier** [comment]
YES for scg
