### ISSUE TITLE
Add Role to Register "Other Accounts"

### ISSUE THREAD

**Issue by canheier** [givingforum/givingforum#164]
Currently only active members can register "other accounts" (users) at their own organization when signing up for an event. Giving staff (and staff admin) the same permissions would be helpful so staff at each RA can register other staff members.

**Comment by EmilyBaron** [comment]
gwp is not interested at this time

**Comment by PhilOhio** [comment]
POH not interested at this time.

**Comment by vrozansky** [comment]
Not much activity in this ticket to move it forward, so I'll assign a deadline of August 10th, 2015 and will resolve then unless there's consensus on how to proceed. Thank you.

**Comment by sgeis** [comment]
Indiana not interested.

**Comment by mtrimbach** [comment]
CNJG not interested

**Comment by MainePhilanthropyCenter** [comment]
MPC is not interested

**Comment by AClay2** [comment]
PSW not interested.

**Comment by kcifone** [comment]
CCP is not interested.

**Comment by kristenruff** [comment]
PNY not interested - just not high enough priority given other pending projects.

**Comment by vrozansky** [comment]
Resolving for lack of interest. Feel free to re-open at a later time. Thank you.
