### ISSUE TITLE
SF / Drupal mapping - Event descriptions

### ISSUE THREAD

**Issue by kristenruff** [givingforum/givingforum#166]
For our larger events (i.e., conferences, multi-day sessions), we often include much longer event descriptions. Currently, the body text in Drupal syncs to the standard description field in SF, which limits text to 3200 characters. We're going to change our mapping so we sync the summary text from Drupal to SF instead. Wanted to flag this in case this is a change others want and we should change the default mappings in the distro.

- Kristen & Allyson

**Comment by vrozansky** [comment]
Let's get some more comments on this ticket please so I know how to proceed with the default mappings in the distro. Thank you.

**Comment by PhilOhio** [comment]
We don't map descriptions into SF but we will go with the group.

**Comment by mtrimbach** [comment]
We don't display the description on that page layout because it's rather ugly with all of the html.  If we changed the distro to map the summary instead of the full, we'd add it to the display and use it in reports as it would be more concise and readable.

**Comment by EmilyBaron** [comment]
GWP would like to map the summary field into SF. The jumble of HTML in the description is not pretty and it would be nice to have the simple summary mapped instead.

**Comment by vrozansky** [comment]
Deadline for this ticket is August 10th. Please weigh in by the deadline. Thank you.

**Comment by canheier** [comment]
NCG / SCG yes

**Comment by EmilyBaron** [comment]
GWP Yes

**Comment by kimsnipes** [comment]
@kristenruff @agoldhagen You are simply mapping the Drupal "Summary" field to Salesforce "Description" field? You didn't create a new field in Salesforce for the Summary, correct?

**Comment by agoldhagen** [comment]
Yes, we just manually changed the mapping so it pulls the summary of the program to the description field.

**Comment by AClay2** [comment]
PSW does not map the description to Salesforce, so no, we're not interested.

**Comment by sgeis** [comment]
Indiana is not interested at this time.

**Comment by MainePhilanthropyCenter** [comment]
MPC is not interested at this time.

**Comment by kcifone** [comment]
CCP is not interested at this time

**Comment by canheier** [comment]
WRAG no

**Comment by vrozansky** [comment]
I'll resolve this ticket as we don't have a consensus for changing the default distro mappings and RAs that are interested in changing this manually can do so on their individual sites. Feel free to re-open for new suggestions or feedback. Thank you.
