### ISSUE TITLE
Apex Error When Adding Leads to a Campaign

### ISSUE THREAD

**Issue by jonstahl** [givingforum/givingforum#168]
When we attempt to add a group of leads to a campaign, the process fails with error: There was an error saving your changes. Apex trigger gf_sf.CampaignMemberAccountLookup caused an unexpected exception, contact your administrator: gf_sf.CampaignMemberAccountLookup: execution of BeforeInsert  caused by: System.NullPointerException: Attempt to de-reference a null object: (gf_sf)

To reproduce:

1) Select a Leads View
2) Select one or more Leads
3) Attempt to Add to a Campaign

**Comment by vrozansky** [comment]
Let's confirm please and decide whether it's a bug that needs to be reported to Brian or not. If not, we can resolve this ticket. Thanks.

**Comment by PhilOhio** [comment]
POH has not encountered this error message but we do not use leads.
