### ISSUE TITLE
Allow Members to View List of Registered Users

### ISSUE THREAD

**Issue by canheier** [givingforum/givingforum#169]
Create a way to allow active members to view the list of registrations for an event. Link for list of registered people could look something like the "manage registrations" tab except we probably just need the view to show name, title, and organization.

**Comment by PhilOhio** [comment]
POH is interested and agrees  with having some level of control for programs with low registration numbers.

**Comment by EmilyBaron** [comment]
GWP is not interested at this time.

**Comment by vrozansky** [comment]
I'm resolving this ticket in favor of #190.
