### ISSUE TITLE
Idea: Node Revision Delete to manage/prune old revisions

### ISSUE THREAD

**Issue by jonstahl** [givingforum/givingforum#171]
Quite a few content types create revisions by default, which is cool. But they do tend to accumulate and slowly bloat the database. It appears that https://www.drupal.org/project/node_revision_delete offers a sane and stable way to manage the accumulation of revisions. It might be sensible to bundle this in a future distro. Not urgent in any way, just putting this here to track the concept.

**Comment by vrozansky** [comment]
Response from ThinkShout below. Please vote.

******************
I have done some research on the suggested Node revision Delete module and it appears to be actively maintained and has relatively few open issues, most of which are feature requests as opposed to bugs, thus making it a viable candidate. There was an issue where it did not play nice with the field collections module, but that issue appears to have been fixed and incorporated into the release of field collections that is in our distribution. (https://www.drupal.org/node/2000690) I will thoroughly test to make sure it isn't wiping out any field collections that we have. I would estimate about 3 hours to install, test and add it to the distribution.

**Comment by jonstahl** [comment]
PNW says yea. :-)

**Comment by AClay2** [comment]
PSW votes in favor of the proposed change.

**Comment by mtrimbach** [comment]
CNJG votes yes.

**Comment by PhilOhio** [comment]
POH votes yes.

**Comment by EmilyBaron** [comment]
GWP says yes

**Comment by vrozansky** [comment]
This was added to our distro in 2.7.5, I believe. Resolving.
