### ISSUE TITLE
Map Capacity (from Product) to Campaign in Salesforce

### ISSUE THREAD

**Issue by canheier** [givingforum/givingforum#174]
It would be helpful for program staff if we could map the event capacity from the product to a capacity field on the campaign object in Salesforce.

**Comment by vrozansky** [comment]
If there's no interest in this ticket, I'll work with SCG individually on this. If there is, please enter your comment/s here. Ideally, we'd hear from all RAs on every ticket. Thank you.

**Comment by EmilyBaron** [comment]
GWP is not interested at this time

**Comment by kristenruff** [comment]
PNY not interested at this time.

**Comment by mtrimbach** [comment]
CNJG not interested at this time

**Comment by PhilOhio** [comment]
POH not interested.
