### ISSUE TITLE
Event that spans multiple months doesn't show calendar graphic for ending month

### ISSUE THREAD

**Issue by sgeis** [givingforum/givingforum#177]
If an event spans multiple months (e.g. Feb 28  – March 2), the event calendar listing graphic will not show the second month. It will only show Feb 28 – 2). We would like it to display the second month (Feb 28 – March 2). See screenshot of Test event (the image graphic only shows the first month)

https://www.diigo.com/item/image/555sg/n39j

Is anyone else having similar issue and would like to correct this either programmatically or via theming?

**Comment by allenlaurie** [comment]
CCP is interested.

[cid:image005.jpg@01D03ADB.4647BDE0]
Laurie Allen | Communications Manager
Connecticut Council for Philanthropy
860-525-5585 | lallen@CTphilanthropy.org<mailto:lallen@CTphilanthropy.org>
221 Main Street, Hartford, CT  06106

CONNECT WITH US: Website<http://www.ctphilanthropy.org/> | Facebook<http://www.facebook.com/CTphilanthropy> | Twitter<http://www.twitter.com/CTphilanthropy> | News<http://www.ctphilanthropy.org/s_ccp/sec.asp?CID=6336&DID=13845> | Blog<http://ctphilanthropynotes.org/>

[ccp1_294]

**Comment by EmilyBaron** [comment]
GWP is not interested at this time

**Comment by jonstahl** [comment]
This seems like a theming issue, not  a core distro issue. Happy to be corrected.

**Comment by vrozansky** [comment]
This was a theming issue and has been corrected for IPA. If anyone is having a similar issue, please contact me. Thank you. Resolving.
