### ISSUE TITLE
Bulk image upload

### ISSUE THREAD

**Issue by jonstahl** [givingforum/givingforum#182]
I am often finding myself wanting to upload multiple images at once. IMCE makes this fairly annoying, however, the module https://www.drupal.org/project/imce_uploader appears promising. Seems like a low-hanging candidate for rolling into a future release. I will probably test it out in the short term outside the distro.

**Comment by vrozansky** [comment]
Now that Nancy Rackleff was hired by ThinkShout to help Alex and Tauno with our project, we're getting movement on dormant tickets. Here's an update from her on this ticket (estimated at 3 hours). Please review and weigh in on whether you'd like this feature. Thank you.

***********
I have researched the IMCE plupload module https://www.drupal.org/project/imce_plupload. And it appears to be compatible with the other modules in the distribution. There is an issue where it doesn’t work when IMCE allowed file extensions are set to “” to allow all files. I checked the current giving forum distribution and the file types are set to “”. There are a couple of possible ways to handle this. A)Provide default configuration that actually lists acceptable file types. OR B)Provide custom code to disable file extension validation if all file types are desired. (https://www.drupal.org/node/1864726#comment-7537367) We would recommend forcing a list of allowed file extensions. Waiving validation entirely is much less secure. Not sure what would happen if someone changes our default list to “*”. Perhaps we can add some help text to warn them it will break if they do.

**Comment by jonstahl** [comment]
PNW says yea. +1 for having some file type upload limitations (starting point might be: jpeg, jpg, gif, png, pdf, doc, docx, ppt, pptx, xls, xlsx, csv)

**Comment by AClay2** [comment]
PSW rarely uploads more than one image at a time, so at the moment, I would say this is not something we need.

**Comment by mtrimbach** [comment]
CNJG has no need at this time.

**Comment by PhilOhio** [comment]
POH doesn't have to do this often but wouldn't hurt to have this option. We are neutral and will go with group concensus.

**Comment by EmilyBaron** [comment]
GWP is not interested

**Comment by vrozansky** [comment]
We actually received this update in release 2.7.4. Resolving.
