### ISSUE TITLE
Tracking Downloads in Google Analytics

### ISSUE THREAD

**Issue by givingforum** [givingforum/givingforum#183]
Bill just re-raised the issue of tracking downloads in Google Analytics. As of right now, you can see that a user arrived on the resource page, but you cannot know for sure he or she download the PDF and actually looked at the resources. 

Seems like there are ways to track downloads (as detailed here: http://www.blastam.com/blog/index.php/2013/03/how-to-track-downloads-in-google-analytics-v2) but we'll need to update the tracking code used on our sites. 

Is your regional interested in tracking these stats? It could be especially helpful for reports or other documents you do a big publicity push on. The Forum is interested.

Thanks.

**Comment by wcorkill** [comment]
Thanks Dan.  CMF Is intersted.

**Comment by allenlaurie** [comment]
Share Analytics measured downloads on our old site. But I have not been able to get it to work on the Drupal site.

[cid:image003.jpg@01D0600C.9DDC9F20]
Laurie Allen | Communications Manager
Connecticut Council for Philanthropy
860-525-5585 | lallen@CTphilanthropy.org<mailto:lallen@CTphilanthropy.org>
221 Main Street, Hartford, CT  06106

Register for Philanthropy's Role in Empowering Change<https://www.ctphilanthropy.org/events/philanthropys-role-empowering-change>
Annual Meeting & Philanthropy Awards on April 30, 2015

CONNECT WITH US: Website<http://www.ctphilanthropy.org/> | Facebook<http://www.facebook.com/CTphilanthropy> | Twitter<http://www.twitter.com/CTphilanthropy> | News<http://www.ctphilanthropy.org/s_ccp/sec.asp?CID=6336&DID=13845> | Blog<http://ctphilanthropynotes.org/>

**Comment by AClay2** [comment]
PSW would be interested, depending on cost.


[PhilanthropySouthwest]

adrienne Clay
Office Manager & Database Administrator
Phone 214-740-1787
Fax 214-740-1790
[facebook]<https://www.facebook.com/PhilanthropySouthwest>[linkedin]<https://www.linkedin.com/company/458770>[twitter]<https://twitter.com/@southwestfdns>
Please note my email address has changed.

**Comment by PhilOhio** [comment]
POH is interested. Tracking downloads would apply to all pages with pdf's etc. not just resources correct?

**Comment by givingforum** [comment]
Correct. This would allow us to track all file downloads.

**Comment by jonstahl** [comment]
I think updating to Universal Analytics is desirable for a number of reasons.

**Comment by allenlaurie** [comment]
Wait, can’t we see downloads in Google Analytics under Behavior/Behavior Flow/Top Events and you can choose PDF or DOC. Or is that if you just open the document?



[cid:image005.jpg@01D08C09.2A0CF170]
Laurie Allen | Communications Manager
Connecticut Council for Philanthropy
860-525-5585 | lallen@CTphilanthropy.org<mailto:lallen@CTphilanthropy.org>
221 Main Street, Hartford, CT  06106

[GOTM-for-signature-orange-A]<https://www.ctphilanthropy.org/resources/get-map>

CONNECT WITH US: Website<http://www.ctphilanthropy.org/> | Facebook<http://www.facebook.com/CTphilanthropy> | Twitter<http://www.twitter.com/CTphilanthropy> | News<http://www.ctphilanthropy.org/s_ccp/sec.asp?CID=6336&DID=13845> | Blog<http://ctphilanthropynotes.org/>

**Comment by jonstahl** [comment]
I believe what’s being discussed here is direct links into the PDF.

**Comment by givingforum** [comment]
For most cases, I think the strategy @allenlaurie laid out above should be sufficient.

I wanted to follow up on an earlier ticket https://github.com/givingforum/givingforum/issues/101, which is upgrading to Universal Analytics. We've re-entered this conversation with ThinkShout and it looks like everything is ready to go.

There are three steps that need to be taken for a successful upgrade:

1. Each regional needs to login to their own Google Analytics and agree to upgrade to Universal Analytics. You may have already done this months ago when UA first rolled out. To check go to the admin tab in GA and look at the middle column. It should look like this: http://www.awesomescreenshot.com/image/245019/4bf0c1571c7f67e032b47844d266a611. If it doesn't, please follow the "Step 1" upgrade instructions at https://developers.google.com/analytics/devguides/collection/upgrade/guide#transfer.

2. The codebase on live site must be updated to include the 7.x.2.x version of the module. ThinkShout has already done this for us.

3. Cache must be cleared. You can easily do this under the home icon in Drupal.

That's all there is to it. Learn more about Universal Analytics at https://support.google.com/analytics/answer/2790010?hl=en.

**Comment by jonstahl** [comment]
Makes sense, thanks Dan! Clarifying question: is GA Module 7.x.-2.x already available to us? And thus we should do these steps now? Or will it be included in a future distro release and we should do it then?

--Jon

**Comment by givingforum** [comment]
The GA Module update is included in the distro 2.7.3 code release which we are pulling to sites now (beginning with test sites). In the mean time, you should update your GA account to Universal Analytics if you have not done so already.

**Comment by jonstahl** [comment]
Thanks for clarifying. Are you sure that updating to UA at Google won’t interfere with our stats before we pull 2.7.3? (I haven’t yet read the fine print.)

**Comment by givingforum** [comment]
Nope, no adverse issues to upgrading early. The Forum’s site has been updated and running UA for awhile now.

**Comment by jonstahl** [comment]
Fabulous!

**Comment by vrozansky** [comment]
Assigning to @dbradyforum to transfer instructions to our Wiki and am resolving this ticket. Feel free to re-open, if needed. Thank you.
