### ISSUE TITLE
Add Second Address to RedHen for Directory Display

### ISSUE THREAD

**Issue by givingforum** [givingforum/givingforum#185]
Florida Philanthropic Network has requested that a second address show in their member directory (such as a billing or shipping address), but while these fields exist in Salesforce they are not currently available in RedHen. We could create the fields as a one off for FPN, but wanted to ask the group if anyone else would be interested in displaying a second address. Once case scenario for this would be a member funder who has a main office elsewhere or is known for being associated with a city outside your region, but also maintains a local office.

If you're interested in adding the second address fields to the distro, please weigh in below.

Thanks,

Dan

**Comment by wcorkill** [comment]
Dan,

I’m not sure we have a need for this at CMF right now, but I think when we were on Impak I solved this issue for a bank with multiple offices  by using child accounts of  the parent account. I think the same logic would still apply and work in SF and work in Drupal.  The only issue would be without customization, the directory wouldn’t show staff from all child accounts on the parent record

The primary office would be listed and then you setup a child account and link back using the Primary Account Field and then the child account has a different address.  This model really works well for organizations with branches (banks) or even a Corporation with a Corporate Foundation at a separate address.  The only other issue to overcome is with memberships.  For that you can give the child (assuming the parent account is a member) is give the child a free/$0 membership so the affiliated contacts get member access.

Bill

From: Dan Brady
Reply-To: givingforum/givingforum
Date: Wednesday, May 6, 2015 at 1:23 PM
To: givingforum/givingforum
Subject: [givingforum] Add Second Address to RedHen for Directory Display (#185)


Florida Philanthropic Network has requested that a second address show in their member directory (such as a billing or shipping address), but while these fields exist in Salesforce they are not currently available in RedHen. We could create the fields as a one off for FPN, but wanted to ask the group if anyone else would be interested in displaying a second address. Once case scenario for this would be a member funder who has a main office elsewhere or is known for being associated with a city outside your region, but also maintains a local office.

If you're interested in adding the second address fields to the distro, please weigh in below.

Thanks,

Dan

**Comment by kimsnipes** [comment]
While Salesforce does have the ability to create parent/child relationships between Account records, I don't know if that is the right solution for the stated need. If the need is solely to capture and show multiple addresses for an Account (other office locations etc), then I don't know if the Parent/Child structure is all that helpful. There is no dynamic connection between a Parent Account and it child(ren), so the membership status field must be controlled manually (along with all the other fields). It also can throw off your member count which is manageable but just one more thing to remember when running reports etc. 

My suggestion would be to utilize the other Address fields on the Account object to show these "other" addresses.

**Comment by AClay2** [comment]
In our former, printed member directory we listed a shipping and a street address which we have captured in Salesforce at the Account level. So we would vote yes for having this option available on the online directory.

**Comment by vrozansky** [comment]
The deadline for this ticket is August 10th, 2015. Please weigh in so we know how to proceed. Thank you.

**Comment by EmilyBaron** [comment]
GWP is not interested.

**Comment by mtrimbach** [comment]
CNJG is not interested at this time.

**Comment by sgeis** [comment]
Indiana is not interested.

**Comment by kristenruff** [comment]
PNY is not interested.

**Comment by vrozansky** [comment]
Insufficient group interest in this task, so I'll resolve the ticket. Folks from Florida and PSW - please feel free to contact me directly if you'd like to complete this task individually. If others develop this need later, please feel free to re-open this ticket or contact me and reference it. Thank you.
