### ISSUE TITLE
Any interest in "non-advertised" events?

### ISSUE THREAD

**Issue by jonstahl** [givingforum/givingforum#186]
We find ourselves wanting to offer registration for a few events that are for targeted audiences and not to be advertised publicly, but also not completely secret/secure. I'm going to do the following customization (which is just point-and-click) but figured I'd share it here if there's interest.

1) Add a field to Events called "Do not Advertise" (boolean). Default to false.
2) Adjust the Filter Criteria on the Event listing views and Search views to exclude nodes where "Do Not Advertise" is true. 

This should result in the Event being findable only if we give you the URL, e.g. via email.

If everybody wants this, this could easily be rolled into the distro in a future release, I reckon.

I think it'd be particularly powerful in combination with #181

**Comment by vrozansky** [comment]
I like this solution. Very simple and easy to implement. Folks, please vote on it here. If most want/need it, we can roll into the distro. If not, it's not difficult to implement individually as well.


On May 11, 2015, at 4:59 PM, Jon Stahl <notifications@github.com<mailto:notifications@github.com>> wrote:


We find ourselves wanting to offer registration for a few events that are for targeted audiences and not to be advertised publicly, but also not completely secret/secure. I'm going to do the following customization (which is just point-and-click) but figured I'd share it here if there's interest.

1) Add a field to Events called "Do not Advertise" (boolean). Default to false.
2) Adjust the Filter Criteria on the Event listing views and Search views to exclude nodes where "Do Not Advertise" is true.

This should result in the Event being findable only if we give you the URL, e.g. via email.

If everybody wants this, this could easily be rolled into the distro in a future release, I reckon.

-

**Comment by kimsnipes** [comment]
Do we want to add that field to the Campaign object in salesforce and add to mappings?

**Comment by jonstahl** [comment]
Personally, I don’t see a great deal of need to do this and don’t plan to in my one-off-implementation — to me this seems like an ephemeral web publishing detail rather than a long-term CRM detail, but if folks are amped about adding this to the distro then I’m not opposed to it. :-)

On May 11, 2015, at 5:51 PM, kimsnipes <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we want to add that field to the Campaign object in salesforce and add to mappings?

**Comment by allenlaurie** [comment]
CCP is interested.

[cid:image004.jpg@01D08C92.0665C0B0]
Laurie Allen | Communications Manager
Connecticut Council for Philanthropy
860-525-5585 | lallen@CTphilanthropy.org<mailto:lallen@CTphilanthropy.org>
221 Main Street, Hartford, CT  06106

[GOTM-for-signature-orange-A]<https://www.ctphilanthropy.org/resources/get-map>

CONNECT WITH US: Website<http://www.ctphilanthropy.org/> | Facebook<http://www.facebook.com/CTphilanthropy> | Twitter<http://www.twitter.com/CTphilanthropy> | News<http://www.ctphilanthropy.org/s_ccp/sec.asp?CID=6336&DID=13845> | Blog<http://ctphilanthropynotes.org/>

**Comment by kristenruff** [comment]
PNY is interested

**Comment by alientezar** [comment]
Donors Forum is interested.
Thanks.


Ali Entezar | Director, Information Technology | Donors Forum
208 South LaSalle, Suite 1540 | Chicago IL 60604 | tel 312-327-8932 | fax 312-578-0103 www.donorsforum.org<http://www.donorsforum.org/>

At our Annual Luncheon on 6/18, performer, educator, and MacArthur “Genius” Liz Lerman will lead us to experience collaboration in new ways. Register through May 22 and get the early-bird rate.<http://donorsforum.org/al41>

**Comment by mtrimbach** [comment]
CNJG interested.



On May 12, 2015, at 6:52 AM, alientezar <notifications@github.com<mailto:notifications@github.com>> wrote:

Donors Forum is interested.
Thanks.


Ali Entezar | Director, Information Technology | Donors Forum
208 South LaSalle, Suite 1540 | Chicago IL 60604 | tel 312-327-8932 | fax 312-578-0103 www.donorsforum.org<http://www.donorsforum.org><http://www.donorsforum.org/>

At our Annual Luncheon on 6/18, performer, educator, and MacArthur "Genius" Liz Lerman will lead us to experience collaboration in new ways. Register through May 22 and get the early-bird rate.<http://donorsforum.org/al41>

**Comment by AClay2** [comment]
PSW is interested.

[PhilanthropySouthwest]

adrienne Clay
Office Manager & Database Administrator
Phone 214-740-1787
Fax 214-740-1790
[facebook]<https://www.facebook.com/PhilanthropySouthwest>[linkedin]<https://www.linkedin.com/company/458770>[twitter]<https://twitter.com/@southwestfdns>
Please note my email address has changed.

**Comment by PhilOhio** [comment]
POH is interested

**Comment by jonstahl** [comment]
Wow, OK, seems like I hit a nerve here. Val, let's talk offline about how I can have Darko do this in a way that is easiest to share back to the distro.

**Comment by vrozansky** [comment]
I'm a bit surprised too :). It's actually a pretty simple customization, so once Darko completes it for the PNW site, I'll take a look and just talk to TS about replicating in the distro. If everyone agrees with Jon that Salesforce sync isn't needed, then there's really little for TS to do. It might be more efficient to just deploy individually anyway, but we'll do the cost analysis when they give us an estimate. 

Thanks and please continue to vote about this feature and the need for SF sync.

**Comment by jonstahl** [comment]
Sounds good. I can have Darko do it then export a feature for you if you like.

**Comment by alientezar** [comment]
It is beneficial for us (Donors Forum) if it syncs with SF. However we will be OK if other members are favoring ‘No need for SF sync’


Ali Entezar | Director, Information Technology | Donors Forum
208 South LaSalle, Suite 1540 | Chicago IL 60604 | tel 312-327-8932 | fax 312-578-0103 www.donorsforum.org<http://www.donorsforum.org/>

At our Annual Luncheon on 6/18, performer, educator, and MacArthur “Genius” Liz Lerman will lead us to experience collaboration in new ways. Register through May 22 and get the early-bird rate.<http://donorsforum.org/al41>

**Comment by PhilOhio** [comment]
POH would like it to sync with SF as well but we are flexible.

**Comment by sgeis** [comment]
Indiana thinks we might use this solution for some events. Having the option to sync with SF would be nice.

**Comment by AClay2** [comment]
PSW would also want to have the option of synching with Salesforce.

[PhilanthropySouthwest]

adrienne Clay
Office Manager & Database Administrator
Phone 214-740-1787
Fax 214-740-1790
[facebook]<https://www.facebook.com/PhilanthropySouthwest>[linkedin]<https://www.linkedin.com/company/458770>[twitter]<https://twitter.com/@southwestfdns>
Please note my email address has changed.

**Comment by jonstahl** [comment]
Alright, I've done this, without Salesforce integration, with the following recipe: 

1) Add field "Invitation only?" on Events. Hidden on all Displays of the Event since this is an admin-only field.

2) Activate indexing of Invitation field in default node index at: /admin/config/search/search_api/index/default_node_index/fields

3) Add criteria of "Invitation Only?" = none to *all displays* of: Events (Search API) view, Events, Extra Blocks view, Site Search view.

**Comment by mtrimbach** [comment]
Jon,

When you say this is done without Salesforce integration, do you mean that the event will not sync at all with Salesforce or just the new field doesn't sync?

**Comment by jonstahl** [comment]
Thanks for asking! Just new field won’t sync. The rest of the Event will function as before.

**Comment by mtrimbach** [comment]
That's what I figured - thanks.   CNJG is good with Jon's option for non-advertised events as it is - we do not need the new field to sync to Salesforce.

**Comment by EmilyBaron** [comment]
GWP is interested and if it doesn't sync to SF, we are okay with that.

**Comment by vrozansky** [comment]
Update: I've been working with themers on this task and added the same functionality to the Forum's site, GWP, and PSW. Tomorrow we'll add it to few other RAs that expressed interest in it on this ticket. I'd like everyone to test it out and report back to me by email if there are any issues. Then, we can individually decide whether it makes sense to map to Salesforce. If so, it shouldn't be too difficult to add this field on the campaign record and map to Drupal. We're still open to considering adding to our common SF package though this interest isn't shared by all (so individual mapping is totally acceptable).

**Comment by vrozansky** [comment]
We re-created this functionality with the help from our themers and applied it to all live sites. On an event node, you’ll see this new check box to create an “Invite Only Event” which can only be accessed through a link shared directly with your invitees. This event will not appear in the events listing or beans. 

This check box does not currently sync to Salesforce, but any given RA can try mapping it individually if this is something they'd like to track.

Resolving this ticket, but please feel free to reopen if there are any additional questions or suggestions.
