### ISSUE TITLE
New Roles for Nonprofits, Advisors, or Associate Members?

### ISSUE THREAD

**Issue by givingforum** [givingforum/givingforum#187]
The Advisory Group has been working with Christina at Maine Philanthropy Center (MPC) to enhance their member directory to reflect their three member types (grantmaker, nonprofit, and consultant) as well as develop a custom Directory of Maine Grantmakers, which includes MPC members and other grantmakers in the state.

It’s becoming clear that to accomplish these tasks, we may need these membership types with new account record types in Salesforce and convert them into unique user roles in Drupal via integration. It is this differentiation by record types in Salesforce that enables different roles/permissions in Drupal. As we talked with other regional associations about this project, several have expressed interest in similar solutions. With that in mind, we have two questions:

1)      Does your regional association have a current or future need to track different membership types in Salesforce/Drupal? Perhaps Nonprofits, Advisors, or Associate Members?
2)      If not, do you have a current or future need to restrict access to certain events for funders, nonprofits, or other audiences? Configure different pricing for these audiences?

If you answer "yes" to either question, what are the distinctions between your membership types/audience?

If there is enough interest, we’ll proceed with adding new account records types to our common Salesforce package and analogous user roles to our Drupal distribution. If not, we can work with ThinkShout on developing instructions for individual RAs.

Donors Forum also has three member types (Grantmaker, Operating Nonprofit, and Advisor Firm) and has developed this functionality with NorthPeak and ThinkShout already. We can migrate it to our SF package and Drupal distro. The estimate for this work isn’t final yet as exact requirements still need to be worked out, but we’re estimating about 5-10 hours for ThinkShout (new roles in the distro, new mappings and logic) and about 5 hours for NorthPeak (new account record types in the package)). This should be a fairly straight forward project, especially if we can all agree on a common naming convention for these record types in SF and user roles in Drupal.

Please provide your answers to the 2 questions above and any additional feedback on this task. We’d like to hear from all participating RAs by the end of this week, if at all possible. Thank you!

**Comment by jonstahl** [comment]
1) PNW does not currently need this. MIE tracks Members (funders) and Affiliate Members (non-funders like financial advisory firms), and for now is probably happy to do so with a picklist on Accounts, but would likely avail itself of this architecture if it were to exist.

2) PNW/MIE don't currently need this. 

As such, we're pretty neutral on this.

![zapp1](https://cloud.githubusercontent.com/assets/882456/7740303/2ccdbe92-ff24-11e4-8082-fb3ce90c9684.jpg)

**Comment by mtrimbach** [comment]
CNJG does not need either of these at this time.

**Comment by EmilyBaron** [comment]
GWP does not need this at this time.

**Comment by sgeis** [comment]
Indiana also does not need this at this time.

**Comment by AClay2** [comment]
PSW does not need at this time either.

**Comment by EmilyBaron** [comment]
GWP is changing our vote :-) We are now interested.

We have been promoting more programs in partnership with other organizations that are open to nonmembers.  This obviously has brought more people to our site and then creating accounts and needing to register for programs.  A nonprofit role will basically add a level to the user roles permissions list.  We can then  customize the permissions and allow us to restrict all kinds of content specifically to nonprofit users.

**Comment by vrozansky** [comment]
The deadline for this ticket is August 10th, 2015.

We discussed this a bit during the user's group session at the conference. If the trend of "not interested" continues, we'll close this ticket, but I'd like to give everyone an opportunity to vote or ask any clarifying questions. Thank you.

**Comment by canheier** [comment]
ncg yes

**Comment by MainePhilanthropyCenter** [comment]
MPC yes

**Comment by PhilOhio** [comment]
POH not interested at this time but perhaps in the future

**Comment by vrozansky** [comment]
Resolving this ticket. Those RAs that expressed interest have either already received new roles or will do so soon. If anyone else develops this need in the future, please search the resolved tickets and re-open as needed. Thank you.
