### ISSUE TITLE
Capacities to show on contact record

### ISSUE THREAD

**Issue by agoldhagen** [givingforum/givingforum#188]
We want to explore showing the capacity from the main account affiliation on a contact record to make it editable through Drupal. This way a user can see/edit their own capacity and either we could manually update those changes on their affiliation record or have it automatically reflect the change on their affiliation through a workflow. 

Is this of interest to anyone else?

**Comment by vrozansky** [comment]
The deadline for this ticket is August 10th, 2015. If there's no interest by this date, we'll assume that this is an individual task for PNY and handle it accordingly. Thank you.

**Comment by agoldhagen** [comment]
I actually think this would be redundant now due to the Drupal update that allows admin contacts to see the capacity of contacts within their organizations and makes this an editable list

**Comment by vrozansky** [comment]
Agreed. Resolving. Feel free to re-open if needed. Thank you.
