### ISSUE TITLE
Printable member directory

### ISSUE THREAD

**Issue by vrozansky** [givingforum/givingforum#191]
This request came from Katy at WRAG and we spent some time evaluating different options. 

Kim explored the possibility of doing this in Salesforce via Conga. Definitely a complicated and time consuming task that will need to be done individually for each RA. Probably not the desired route.

Doing this in Drupal isn't simple either but there's a possibility of all RAs using a single solution (with some individual tweaks). I consulted with ThinkShout and themers, both of which initially pushed back saying that it'll be fairly complicated and taxing on our system. After further exploration, themers came up with a workable solution.

If we go the dynamic PDF route (generate printable directory in a PDF), it’ll take about 3 days of work to customize (24 hours or so). This solution will most likely use this module – http:///drupa.org/project/print. Then different libraries will need to be installed such as - https://www.drupal.org/node/306882. Pantheon and ThinkShout will need to install this in our distro -  https://pantheon.io/docs/articles/sites/external-libraries/ - and then configuration work will follow. It’ll include such elements as: cover page (with footer, header, margins), header with image that’s different for each page, footer with URL and page, directory (orgs and contacts listings) without tables for proper formatting. There might be some room to simplify things and cost share if we could agree on some uniform look/feel. 

Please note that one of the problems with dynamically generated PDFs is that it takes a bunch of memory to generate an initial PDF.

If we go with a pure HTML/CSS solution (no PDF - similar to printable event rosters in ticket #190), we can shave a whole day of development (16 hours or so). It’ll be a custom view/module that lists orgs and contacts in member directory (RAs will need to confirm that all members have indeed synced to Drupal and are displaying in member directory). Then configuration, styles, and alter tags to make everything print compatible. Won’t be as pretty as PDF, but users could print directly from the browser.

Given the complexity of this task (either approach), I'd absolutely suggest including a margin of at least 30% for these estimates. Here's what they'll look like in terms of actual dollars:

1. Dynamic PDF - about $3,150. If approved by all the Drupal-using RAs, it'll be less than $200 each.

2. HTML/CSS solution - about $2,100. If split among all the Drupal-using RAs, it'll be about $125 per RA.

Please cast your vote on this task. Thank you.

**Comment by kristenruff** [comment]
That's an impressive solution.

But we have finally stopped hearing calls from our members for a print directory so this wouldn't be a priority for us right now.

Kristen Ruff - PNY


On Jul 15, 2015, at 8:48 PM, vrozansky <notifications@github.com<mailto:notifications@github.com>> wrote:


This request came from Katy at WRAG and we spent some time evaluating different options.

Kim explored the possibility of doing this in Salesforce via Conga. Definitely a complicated and time consuming task that will need to be done individually for each RA. Probably not the desired route.

Doing this in Drupal isn't simple either but there's a possibility of all RAs using a single solution (with some individual tweaks). I consulted with ThinkShout and themers, both of which initially pushed back saying that it'll be fairly complicated and taxing on our system. After further exploration, themers came up with a workable solution.

If we go the dynamic PDF route (generate printable directory in a PDF), it’ll take about 3 days of work to customize (24 hours or so). This solution will most likely use this module – http:///drupa.org/project/print. Then different libraries will need to be installed such as - https://www.drupal.org/node/306882. Pantheon and ThinkShout will need to install this in our distro - https://pantheon.io/docs/articles/sites/external-libraries/ - and then configuration work will follow. It’ll include such elements as: cover page (with footer, header, margins), header with image that’s different for each page, footer with URL and page, directory (orgs and contacts listings) without tables for proper formatting. There might be some room to simplify things and cost share if we could agree on some uniform look/feel.

Please note that one of the problems with dynamically generated PDFs is that it takes a bunch of memory to generate an initial PDF.

If we go with a pure HTML/CSS solution (no PDF - similar to printable event rosters in ticket #190<https://github.com/givingforum/givingforum/issues/190>), we can shave a whole day of development (16 hours or so). It’ll be a custom view/module that lists orgs and contacts in member directory (RAs will need to confirm that all members have indeed synced to Drupal and are displaying in member directory). Then configuration, styles, and alter tags to make everything print compatible. Won’t be as pretty as PDF, but users could print directly from the browser.

Given the complexity of this task (either approach), I'd absolutely suggest including a margin of at least 30% for these estimates. Here's what they'll look like in terms of actual dollars:

  1.  Dynamic PDF - about $3,150. If approved by all the Drupal-using RAs, it'll be less than $200 each.

  2.  HTML/CSS solution - about $2,100. If split among all the Drupal-using RAs, it'll be about $125 per RA.

Please cast your vote on this task. Thank you.

**Comment by EmilyBaron** [comment]
GWP isn't interested either. We stopped printing the directory when the new website launched and we haven't had any requests for the printed version anymore either! wahoo!

**Comment by PhilOhio** [comment]
POH isn't interested. We also stopped the printable directory once our new site was up and have had no requests for one.

**Comment by canheier** [comment]
SCG won't need this either.

**Comment by vrozansky** [comment]
As we agreed at the conference last week, all tickets will be given a 2-week deadline period for voting. If your RA does not enter a vote within the allocated timeframe, a vote of YES will entered on its behalf. All RAs are encouraged to vote as quickly as possible in order to move tickets forward and not hold up any partner RAs. Thank you for your understanding.

The deadline for this ticket is August 10th, 2015.

**Comment by canheier** [comment]
NCG- no

**Comment by sgeis** [comment]
Indiana is not interested.

**Comment by mtrimbach** [comment]
CNJG not interested

**Comment by MainePhilanthropyCenter** [comment]
MPC does not need a print member directory, but is interested in a print version of our Directory which probably is too specific for this group.

**Comment by kcifone** [comment]
CCP is not interested now but may be in the future

**Comment by capitalgrits** [comment]
WRAG is still interested in exploring a "print on demand" directory. We still have a number of members (and a few staff member, ahem) that like the printed directory :)

**Comment by wcorkill** [comment]
CMF is not interested

**Comment by kcifone** [comment]
CCP is not interested now but might be in the future

**Comment by vrozansky** [comment]
I'll resolve this ticket. @capitalgrits - please contact me directly if WRAG wants to pursue this individually. Thank you.

**Comment by canheier** [comment]
WRAG will not pursue at this time
