### ISSUE TITLE
IDEA: Include XML Sitemap module to make our sites easier to crawl

### ISSUE THREAD

**Issue by jonstahl** [givingforum/givingforum#199]
I'm doing a quick SEO review of our site, and one thing I'm noticing is that we don't have XML Sitemaps, which make it easier for Google and other search engines to crawl the site. https://www.drupal.org/project/xmlsitemap seems to be the widely-used Drupal module that provides this, perhaps it is worth including in the distro.

**Comment by kristenruff** [comment]
Sounds like a good idea.

**Comment by vrozansky** [comment]
We had a fairly lengthy exchange with ThinkShout on this. Lev mentioned that this particular module has been known to cause some performance issues, but more work is being done on it and configuration can help. The alternative is to use a third-party service to generate these sitemaps and then manually submit them to major search engines for SEO (not ideal!).

We decided to install the module in the distro in the OFF state and allow selected RAs to turn it on, configure it, and see how well it performs. The estimate for this work is 2 hours and will include the following:
•	Add the xmlsitemap modules to the build.
•	Do a fresh build.
•	Enable and test the module to make sure it plays nice with the distribution.
•	Include instructions in the distribution for the RAs to add a couple of lines of custom code to their site.settings.php files to ensure that the sitemap is not submitted from dev and test environments.

The estimate is reasonable and we have few volunteer RAs to give it a try. If we split this cost among all the participating Drupal RAs, the cost is about $50 and I'm including additional configuration work provided that it's not complicated and can be transferred to each site. If we simply split the 2 hours above, it's less than $15 per RA.

Please respond no later than November 9th. Thank you.

**Comment by jonstahl** [comment]
+1.

**Comment by kristenruff** [comment]
Sounds fine to us.


______________________________________________
Kristen M. Ruff : Vice President, Member Services
Philanthropy New York
1500 Broadway, 7th Floor, New York, NY 10036
212.714.0699 x 221 | kruff@philanthropynewyork.org<mailto:kruff@philanthropynewyork.org>
www.philanthropynewyork.org<http://www.philanthropynewyork.org/> | @PhilanthropyNY<http://twitter.com/#!/philanthropyny>

Did you know? PHILANTHROPY NEW YORK has MOVED!
Our new home is 1500 Broadway, 7th Floor (at 43rd Street).

**Comment by wcorkill** [comment]
Sounds like a good cost effective solution.  Count us in.

**Comment by EmilyBaron** [comment]
Sounds fine for GWP also.

**Comment by mtrimbach** [comment]
Fine with CNJG

**Comment by AClay2** [comment]
PSW is interested.

**Comment by PhilOhio** [comment]
POH is interested.

**Comment by vrozansky** [comment]
Release 2.7.7 includes a number of modules with XML features. They're turned off by default, so interested RAs should turn them on by following the instructions that I posted on Basecamp (with images) - https://givingforum.basecamphq.com/projects/8670639-network-collaborations-drupal/posts/96282681/comments. 

Alternatively, feel free to contact me and I'll do this for you. Thank you. Resolving...
