### ISSUE TITLE
Admin Contact - Approving New Contacts

### ISSUE THREAD

**Issue by agoldhagen** [givingforum/givingforum#201]
Currently, we manage our approval process for new contacts where we change their account information, run cron, and then approve them on Drupal. With the new administrative contact capabilities, contacts that are added by the admin contact are automatically active on the website. 

We are interested in creating additional features to the administrative contact capabilities in drupal/salesforce. At the moment, when an administrative contact adds a staff member the contact is automatically active in drupal but comes into salesforce with the ghost account (first/last name) and an affiliation to the member account. This means they look like they are a member but they don’t receive any membership privileges since their account lookup is a fake account. 

This presents two problems: 
1.	If someone is to login before we change their account name, from their end they would look as if they are members but once they try to register for an event or access member-only webpages the website would tell them they do not have access. This seems unnecessarily confusing since we can trust the admin contact to know their staff roster list. 
2.	In salesforce, once you change the account name it creates a second affiliation. Since we just got rid of duplicate affiliations, I don’t want to have to keep deleting this second affiliation. The flow/process builder we all implemented doesn’t necessarily catch these second affiliations since they won’t have the sequential names. 

Val has had conversations with ThinkShout about linking the administrative contact edit capabilities directly to the account lookup field. We are interested in giving administrative contacts the ability to add staff that are automatically approved and given membership status in drupal and correctly affiliated with their organization (through the look up field and affiliation). This would cut out the staff time needed to edit/approve contacts added by these trusted sources. 

TS has estimated this cost at 6 hours.

**Comment by alientezar** [comment]
Forefront is interested in this fix.
Thanks.

Ali Entezar
Director, Information Technology

Forefront
208 South LaSalle, Suite 1540
Chicago, IL 60604
312-327-8932
aentezar@myforefront.org<mailto:aentezar@myforefront.org>
[cid:image001.png@01D12E72.3B9E8910]<http://myforefront.org/>

Donors Forum is now Forefront.

**Comment by canheier** [comment]
YES PLEASE for SCG

**Comment by vrozansky** [comment]
Here's an update from Nancy at TS on this ticket. Please review and weigh in if there's something in Salesforce that we can adjust. Thanks.

******************
"Nancy Rackleff: Alex and I worked on this today:
•	We added an entity_presave function code to set the value of the organization when creating a contact from the redhen/org/%/connections/add form.
•	We changed the direction of the salesforce mappings for the Account ID (Organization) field on general contacts from “SF to Drupal” to “Sync” so the data will get pushed to Salesforce when a new contact is created. (We are not certain that change would not have other negative ramifications. Let us know if you can think of any. The Drupal user does not have access to change the value of that field.)

What we discovered though, is that no matter what we send, Salesforce creates and account for that contact with the same name as the contact. We did find that if we then resave the contact on the Drupal side, it will then get pushed up to Salesforce and the Account Name field gets corrected and linked to the proper organization account, but the original account with the same name as the contact does not get deleted.

We believe there must be a rule or trigger on the Salesforce side that is ignoring what we are sending when the initial contact is created and automatically creating that account with the same name as the user. Is that something you could look into on the Salesforce side?
We did this work on a local instance of the integration site, so there are new contacts in that Salesforce instance. I can delete them later."

**Comment by AClay2** [comment]
PSW is definitely in support of this proposed change.

[PhilanthropySouthwest]

adrienne Clay
Office Manager & Database Administrator
Phone 214-740-1787
Fax 214-740-1790
[facebook]<https://www.facebook.com/PhilanthropySouthwest>[linkedin]<https://www.linkedin.com/company/458770>[twitter]<https://twitter.com/@southwestfdns>

**Comment by gabriellehana** [comment]
this is a yes for NCG!

**Comment by PhilOhio** [comment]
POH is interested.

**Comment by EmilyBaron** [comment]
GWP is interested

**Comment by capitalgrits** [comment]
WRAG is interested

**Comment by mtrimbach** [comment]
CNJG is interested

**Comment by MainePhilanthropyCenter** [comment]
MPC is maybe interested but need a better sense of the total cost and whether it's specific to users added by administrative contacts (Val or Courtney: is this related to a new user account not being affiliated with a current member after they select that organization?)

**Comment by alientezar** [comment]
Same here at Forefront.


Ali Entezar
Director, Information Technology

Forefront
208 South LaSalle, Suite 1540
Chicago, IL 60604
312-327-8932
aentezar@myforefront.org<mailto:aentezar@myforefront.org>
[cid:image001.png@01D159A9.68997E90]<http://myforefront.org/>

Donors Forum is now Forefront.

**Comment by vrozansky** [comment]
I haven't updated this ticket in a while, but I've been back and forth with Brian and Alex on this and we have a fix in place committed to 2.7.7.1. We'll add few more things to this release and then roll it out.

@MainePhilanthropyCenter - it is related. Not exactly the same thing, but definitely related.

I see a number of votes on this task and we'll be treating it as a core Drupal upkeep. It's really something that should be in the distro and not on individual sites. Thank you. Resolving.
