### ISSUE TITLE
Sorting SF fields by alpha in mappings

### ISSUE THREAD

**Issue by canheier** [givingforum/givingforum#205]
SCG asked ThinkShout to change the SF field lists in the SF mappings in drupal to sort by alpha instead of date created: http://www.awesomescreenshot.com/image/879200/a9d86dda59e73a37c97d5b36cdaf1be0. If interested, this will part of the next code update.

**Comment by vrozansky** [comment]
Thanks @canheier. TS quoted this at 4 hours and completed the task. If divided among all Drupal-participating RAs, it'll be $35 each. Please vote. Thank you.

**Comment by alientezar** [comment]
Forefront is OK with it.
Thanks.


Ali Entezar
Director, Information Technology

Forefront
208 South LaSalle, Suite 1540
Chicago, IL 60604
312-327-8932
aentezar@myforefront.org<mailto:aentezar@myforefront.org>
[cid:image001.png@01D15767.295F8970]<http://myforefront.org/>

Donors Forum is now Forefront.

**Comment by PhilOhio** [comment]
POH is fine with it

**Comment by kristenruff** [comment]
Fine with PNY


______________________________________________
Kristen M. Ruff : Vice President, Member Services
Philanthropy New York
1500 Broadway, 7th Floor, New York, NY 10036
212.714.0699 x 221 | kruff@philanthropynewyork.org<mailto:kruff@philanthropynewyork.org>
www.philanthropynewyork.org<http://www.philanthropynewyork.org/> | @PhilanthropyNY<http://twitter.com/#!/philanthropyny>

Did you know? PHILANTHROPY NEW YORK has MOVED!
Our new home is 1500 Broadway, 7th Floor (at 43rd Street).

**Comment by mtrimbach** [comment]
Fine with CNJG

**Comment by AClay2** [comment]
PSW is in.

**Comment by wcorkill** [comment]
CMF is in.

**Comment by EmilyBaron** [comment]
GWP is in

**Comment by MainePhilanthropyCenter** [comment]
MPC is in

**Comment by alientezar** [comment]
Forefront is not interested.

Ali Entezar
Director, Information Technology

Forefront
208 South LaSalle, Suite 1540
Chicago, IL 60604
312-327-8932
aentezar@myforefront.org<mailto:aentezar@myforefront.org>
[cid:image001.png@01D159A9.AD6FB7A0]<http://myforefront.org/>

Donors Forum is now Forefront.

**Comment by lpatinomcf** [comment]
MCF is interested.

**Comment by sgeis** [comment]
IPA is fine with the mappings either way.

**Comment by kcifone** [comment]
Fine with CCP

**Comment by vrozansky** [comment]
This has been done and added to the upcoming release. Resolving.
