### ISSUE TITLE
Bulk Actions for KB Management

### ISSUE THREAD

**Issue by givingforum** [givingforum/givingforum#41]
It'd be nice if we had some bulk actions on the Knowledgebase Management page. I'm thinking of Publish/Unpublish, Private/Not Private, Shared, and Reviewed. We'll be reviewing each item as it comes in, but to allow for alternative workflows, we might want to build in some options for bulk actions.

For example, rather than going through the process one by one, folks might want to click into each, see what it's about, and then go back to the big list and be able to mark multiple as reviewed and publish them as a group.

**Comment by vrozansky** [comment]
This has been completed. Please contact @givingforum if you need more information. Thank you. Resolving.
