### ISSUE TITLE
Profile Matching

### ISSUE THREAD

**Issue by givingforum** [givingforum/givingforum#46]
Users of a member association’s website may find other users of that website according to the interests and skills they have entered in their profile. Interests and skills are “free tagging” vocabularies in Drupal. This allows users to add an interest or skill to the vocabulary by typing it in their profile. As a user begins typing in either the interest or skill field, the interface will offer auto-complete options based on interests or skills that have already been entered. This auto-complete feature is built-in to Drupal. From his or her own profile, a user can click on an interest s/he has added and see a list of the other users of that association’s site that have added the same interest. The same scenario will also apply to skills. A further refinement would be a module that automatically identifies other site users that have two or more skills or interests in common with the user who is browsing profiles. 

Are we collecting identities from other spaces in the drupal or salesforce profile? e.g. my linked-in, facebook, blog, twitter accounts, my affiliations in other affinities GEO, ASF, COF, GIH, etc?

**Comment by vrozansky** [comment]
Resolving for now with Parking Lot tag. Can be re-opened by any RA that developed this need/interest. Thank you.
