### ISSUE TITLE
Jobs Bank

### ISSUE THREAD

**Issue by givingforum** [givingforum/givingforum#48]
Searchable jobs bank for each RA. Original idea had been a linked national jobs bank. There is an existing module called Listing that aims to provide job bank functionality. Alternatively, job listings could be handled with a content type and Views. 

We should think about the eCommerce implications of this. How many RAs are providing this for free vs using for additional revenue? POH offers for free to members, small charge for non-members.

**Comment by vrozansky** [comment]
Closing this ticket in favor of a new one that I'm about to file pertaining to the work that MCF is about to undertake with ThinkShout.
