### ISSUE TITLE
Add User to "Group" if they purcahse an item/registration online

### ISSUE THREAD

**Issue by givingforum** [givingforum/givingforum#66]
If a user buys an item/registration form the website add them to a selected group, this allows you to setup content ahead of time and provide materials to only those that purchased/ordered a specific item.

CMF: This also allows this to happen in real time and not require staff to add campaign members to a new group/committee manually.

**Comment by vrozansky** [comment]
Resolving due to the lack of interest, but keeping the Parking Lot tag so we can re-open at a later time. Thank you.
